### ISSUE TITLE
Handling more than 1 type per name?

### ISSUE THREAD

**Issue by gdower** [Sp2000/coldp#24]
In order to handle multiple types per name, we might need to move types into a separate table.

**Comment by mdoering** [comment]
Like `Taxon.referenceID` typeMaterial is allowed to contain multiple values  by concatenating them.
I see we do miss the expected delimiter in the field definition. I would suggest to use `|` as commas which we use for `Taxon.referenceID` is likely to be used inside the value itself.

**Comment by mdoering** [comment]
in case the typeReferenceID and typeStatus differ for each type specimen things get a bit messy

**Comment by mdoering** [comment]
@gdower would you think its better to handle types with a dedicated TypeSpecimen entity? it becomes more difficult to map, but more accurate.

**Comment by gdower** [comment]
Scarabs has ~1500 names with more than 1 type almost all of which have a different type status, and some have different type references. I think it would be better organized and probably easier for most users to handle in a separate NameType table.

**Comment by mdoering** [comment]
A separate entity makes sense. I just wanna avoid an intermediate many-many "table".
If we attach types only to original names / protonyms and not recombinations the vast majority of types is unique to a name. For illegal names, conserved ones etc this might be different.

Options
 1. types have a unique ID and you refer to them from the name and allow to concat multiple type ids like we do with referenceID 
 1. types have a nameID property that can also be a list if the same type refers to multiple names
 1. separete TypeDesignation table that connects a single nameID with a typeID and also takes the referenceID to refer to a publication for the (subsequent) designation. (in the scenarios above the referenceID will be part of the types table instead.

**Comment by mdoering** [comment]
what about this?
<img width="533" alt="Bildschirmfoto 2019-12-17 um 15 43 34" src="https://user-images.githubusercontent.com/327505/71005526-124eae00-20e4-11ea-9425-8384684a4f2e.png">

**Comment by mjy** [comment]
Of course the questions will come with the collection object fields, host,
date, locality.  People are going to want catalog number, male, female,
etc.  Practically an infinite number of fields.

In other words this is a stop-gap solution for the real model that has a
seperate concept for CollectionObjects. I would propose that you have 3
fields if you go this route, all verbatim - verbatim collecting events,
verbatim determinations, and verbatim other labels.  Since the value in the
fields will be completely uncomputable anyways people can stuff what they
want into these three and move on.

For what it's worth TypeMaterial in TW is the relationship between a
nomenclatural name and a specimen, nothing more.  It's also important to
note that this is not the same thing as a taxon determination because this
relationship is objective, and a taxon determination is subjective.

So, no easy answer on your drift towards the TW model ;)

**Comment by mdoering** [comment]
It's tempting to flesh out all properties, but that is indeed a beast as you can see in Darwin Core. Also what use is it to have parsed out specimen data? All we really interested in is the type status, the reference in case of subsequent designations, the human readable citation and if existing a link to the specimen elsewhere. I doubt having type locality separate from collector, institution code, catalogue number, collecting date, host, etc helps us in any way. Maybe its best to stick with the most simple approach we had when it was part of the Name entity:

 - nameID
 - citation, [see EJT guidelines](http://sciencepress.mnhn.fr/sites/default/files/material_citations_formatting_guide.pdf)
 - (type) status
 - referenceID

**Comment by mdoering** [comment]
... country or coordinate could be useful to present the specimen on a map

**Comment by mdoering** [comment]
<img width="520" alt="Bildschirmfoto 2019-12-17 um 18 08 17" src="https://user-images.githubusercontent.com/327505/71018131-3916df80-20f8-11ea-8a11-5e3f13401624.png">
